language: php
env:
  global:
    - PHP_PROTOBUF_VERSION=0.10
php:
  - 5.3

install:
  - sh ./bin/install-php-protobuf.sh

before_script:
  - mkdir build && cd build
  - php ../php-protobuf/protoc-php.php --use-namespaces src/searchrequest.proto

script:
  - php -l pb_proto_searchrequest.php
